### ISSUE TITLE
Cockpit shows logrotate failed on Pi

### ISSUE THREAD

**Issue by GitMarshallBill** [NEMSLinux/nems-admin#11]
Log rotate shows failed in Cockpit on Pi only. VM is fine.  systemctl status logrotate also shows error 
nems logrotate[27179]: error: error running non-shared prerotate script for /var/log/nems/memtest.log of '/var/log/nems/*.log /var/log/nems/*/*.log

**Comment by NEMSLinux** [comment]
Thank you. Confirmed: it appears the exclusions in the logrotate _nems.conf_ are not compatible with the newer version of logrotate in NEMS Linux 1.6 on the Raspberry Pi. When your memtest.log file exceeded 1 MB, it triggered the log rotation, but then saw the incompatible exclusion and crashed logrotate.

Fixed: I've changed the logrotate config to rotate specific log files rather than globs with exclusions.

See: https://github.com/NEMSLinux/nems-migrator-data/commit/b2e9b63b68fab1964045093b537ba68ee2f0182f
